require('plugins')
require('keymaps')
require('mason-config')
require('code-completion')
require('statusbar')
require('toggleline')
require('treesitter')
require('colortheme')
require("ibl").setup()
require('nvimtree')
require('comments')
require('bufline')
require	('colortheme')
